FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags "-s -w" -o app ./cmd/api

FROM alpine:latest
ENV SERVER_PORT=8080
WORKDIR /root/

COPY --from=builder /app/app .
RUN chmod +x ./app
EXPOSE 8080
CMD ["./app"]